src/AppBundle/Entity/Evaluation.php
<?php

namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Evaluation
 *
 * @ORM\Table(name="evaluation")
 * @ORM\Entity(repositoryClass="AppBundle\Repository\EvaluationRepository")
 */
class Evaluation
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;
    
    /**
     * @ORM\OneToMany(targetEntity="Mark", mappedBy="evaluation")
     */
    private $marks;
    
    /**
     * @var \DateTime
     *
     * @ORM\Column(name="createdAt", type="datetime", nullable=true)
     */
    private $createdAt;
    
    /**
     * @var type 
     * @ORM\ManyToOne(targetEntity="EvaluationType")
     * @ORM\JoinColumn(nullable=false)
     */
    private $evaluationType;
    
    /**
     * @var type 
     * @ORM\ManyToOne(targetEntity="AffectedProgram", inversedBy="evaluations")
     * @ORM\JoinColumn(nullable=false)
     */
    private $affectedProgram;
    
    /**
     * @var type 
     * @ORM\ManyToOne(targetEntity="Sequence", inversedBy="evaluations")
     * @ORM\JoinColumn(nullable=false)
     */
    private $sequence;

    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=255, nullable=true)
     */
    private $name;


    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    public function getCode()
    {
        return $this->getId()."/".$this->getAffectedProgram()->getSection()->getId();
    }
    
    public function getAverage()
    {
        $markAverage = null;
        $nb = 0;
        foreach ($this->getMarks() as $mark){
            $nb = $nb + 1;
            $markAverage = $markAverage + $mark->getValue();
        }
        
        return $markAverage/$nb;
    }
    
    public function __toString() {
        if($this->name){
            return $this->name;
        }
        
        return 'Undefined Name';
    }

    /**
     * Set name
     *
     * @param string $name
     *
     * @return Evaluation
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }
    /**
     * Constructor
     */
    public function __construct()
    {
        $this->marks = new \Doctrine\Common\Collections\ArrayCollection();
    }

    /**
     * Set createdAt
     *
     * @param \DateTime $createdAt
     *
     * @return Evaluation
     */
    public function setCreatedAt($createdAt)
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    /**
     * Get createdAt
     *
     * @return \DateTime
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    /**
     * Add mark
     *
     * @param \AppBundle\Entity\Mark $mark
     *
     * @return Evaluation
     */
    public function addMark(\AppBundle\Entity\Mark $mark)
    {
        $this->marks[] = $mark;

        return $this;
    }

    /**
     * Remove mark
     *
     * @param \AppBundle\Entity\Mark $mark
     */
    public function removeMark(\AppBundle\Entity\Mark $mark)
    {
        $this->marks->removeElement($mark);
    }

    /**
     * Get all the related marks; ideally, it should be
     * marks of all the students that belong to the
     * the section targeted by the evaluation
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getMarks()
    {
        return $this->marks;
    }

    /**
     * Set evaluationType
     *
     * @param \AppBundle\Entity\EvaluationType $evaluationType
     *
     * @return Evaluation
     */
    public function setEvaluationType(\AppBundle\Entity\EvaluationType $evaluationType)
    {
        $this->evaluationType = $evaluationType;

        return $this;
    }

    /**
     * Get evaluationType
     *
     * @return \AppBundle\Entity\EvaluationType
     */
    public function getEvaluationType()
    {
        return $this->evaluationType;
    }

    /**
     * Set sequence
     *
     * @param \AppBundle\Entity\Sequence $sequence
     *
     * @return Evaluation
     */
    public function setSequence(\AppBundle\Entity\Sequence $sequence)
    {
        $this->sequence = $sequence;

        return $this;
    }

    /**
     * Get sequence
     *
     * @return \AppBundle\Entity\Sequence
     */
    public function getSequence()
    {
        return $this->sequence;
    }

    /**
     * Set section
     *
     * @param \AppBundle\Entity\Section $section
     *
     * @return Evaluation
     */
    public function setSection(\AppBundle\Entity\Section $section)
    {
        $this->section = $section;

        return $this;
    }


    /**
     * Set affectedProgram.
     *
     * @param \AppBundle\Entity\AffectedProgram $affectedProgram
     *
     * @return Evaluation
     */
    public function setAffectedProgram(\AppBundle\Entity\AffectedProgram $affectedProgram)
    {
        $this->affectedProgram = $affectedProgram;

        return $this;
    }

    /**
     * Get affectedProgram.
     *
     * @return \AppBundle\Entity\AffectedProgram
     */
    public function getAffectedProgram()
    {
        return $this->affectedProgram;
    }
}

src/AppBundle/Controller/DefaultController.php
<?php

namespace AppBundle\Controller;

use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\JsonResponse;
use AppBundle\Entity\Mark;
use AppBundle\Helper\CSVTypes;

use Ddeboer\DataImport\ValueConverter\StringToObjectConverter;
use Doctrine\DBAL\Exception\UniqueConstraintViolationException;
use Ddeboer\DataImport\Reader\CsvReader;
use Ddeboer\DataImport\Workflow;
use Ddeboer\DataImport\Writer\DoctrineWriter;
use Ddeboer\DataImport\Workflow\StepAggregator;
use dompdf\dompdf;


class DefaultController extends Controller
{
    public function indexAction(Request $request)
    {
        //echo $request->getDefaultLocale();exit;
        //$this->get('translator')->setlocale('en');
        //$translatedMessage = $this->get('translator')->trans('hello');
        //return new Response($translatedMessage.' '.$request->getLocale());
        //$request->setlocale('en');
        return $this->render("@App/Default/front.html.twig");
    }
    
    public function settingAction()
    {
        $em = $this->getDoctrine()->getManager();
        $setting = $em->getRepository('AppBundle:Setting')->findOneBy(array('name' => 'setting'));
        
        if(!$setting){
            throw $this->createNotFoundException('No object setting found');
        }
        
        return $this->redirectToRoute('admin_app_setting_edit', array('id' => $setting->getId()));   
    }
    
    public function markInputAction($section_id, $evaluation_id)
    {
        //Get all student for the the right section
        $em = $this->getDoctrine()->getManager();
        //We need the evaluation
        $evaluation = $em->getRepository('AppBundle:Evaluation')->find($evaluation_id);
        //Make sure the evaluation is related to the current section
        //Exemple we want to avoid a situation where 1ere G3B evaluation
        //is loaded when student of 1ere G3A suppose to receive mark...
        if($evaluation->getAffectedProgram()->getSection()->getId() == $section_id){
            $section = $em->getRepository('AppBundle:Section')->find($section_id);
            $students = $section->getStudents();
            return $this->render("@App/Teacher/input_mark.html.twig", array('students' => $students, 
                                                                            'section' => $section,
                                                                            'evaluation' => $evaluation));
        }else{
            throw $this->createNotFoundException('Evaluation #ID: '.$evaluation_id.' & Section #ID: '.$section_id.' are not related.');
        }
        
    }
    
    
    public function markUploadAction(Request $request)
    {
        
        $em = $this->getDoctrine()->getManager();
        //Make sure the request content data
        if($request->request->get('data')){
            //Get all the necessary variable
            $inputData = $request->request->get('data');
            $markValue = $inputData['mark'];
            $student = $em->getRepository('AppBundle:Student')->find($inputData['student_id']);
            $evaluation = $em->getRepository('AppBundle:Evaluation')->find($inputData['evaluation_id']);
            if(!$student || !$evaluation){
                throw $this->createNotFoundException('User of #ID '.$inputData['student_id'].' or Evaluation not found in DB');
            }
            //check whether this student all ready have a mark for the current evaluation
            foreach ($evaluation->getMarks() as $mark){
                if($mark->getStudent()->getId() == $student->getId()){
                    if($this->isGranted('ROLE_LEVEL2')){
                        //keep the old mark value
                        $oldMark = $mark->getValue();
                        //update the mark
                        $mark->setValue($markValue);
                        $em->persist($mark);
                        $em->flush();
                        //Set the feed back message and translate it
                        $translator = $this->get('translator');
                        $msg1 = 'Mark updated from';
                        $msg2 = 'to';
                        $translator->trans($msg1); 
                        $translator->trans($msg2);
                        return new JsonResponse($msg1.' '.$oldMark.' '.$msg2.' '.$mark->getValue());
                    }else{
                        return new JsonResponse('[Error] This student all ready have a mark:'.$mark->getValue());
                    }
                    
                }
            }
            //create new Mark object
            $markObject = new Mark();
            $markObject->setValue($markValue);
            $markObject->setEvaluation($evaluation);
            $markObject->setStudent($student);
            $em->persist($markObject);
            $em->flush();
            
            return new JsonResponse('[ok] Sucessfull mark submission for '.$student->getName().' Mark: '.$markValue);
        }
                
        return new JsonResponse('Error: Wrong parameters.');
    }
    
    /*
     * this method aims to Build mark table for all student belonging to one section
     */
    public function markTableAction($section_id)
    {
        //Make sure GenerateMarkTableSTDRequirement() return true
        if($this->get('app.utilsSTD')->checkGenerateMarkTableSTDRequirements()){
            //Continue (Do nothing)
        }else{
            //Return server message such as you should do x, y, ... before generating markTable (Stop)
        }
        //Get the buildMarkTableHandler Service
        $buildMarkTableHandler = $this->get('app.build_marktable_handler');
        //Disable the profiler in order to see the printable template perfectly
        if ($this->container->has('profiler'))
        {
            $this->container->get('profiler')->disable();
        }
        //We will need DB connection
        $em = $this->getDoctrine()->getManager();
        //We will need the setting in order to set the school name, ...
        $setting = $em->getRepository('AppBundle:Setting')->findOneBy(array('name' => 'setting'));
        if(!$setting){
            throw $this->createNotFoundException('Setting not found');
        }
        //Get the section from DB
        $section = $em->getRepository('AppBundle:Section')->find($section_id);
        //Generate the markTables of the given section
        $markTable = $buildMarkTableHandler->generateMarkTable($section, $setting);
        //Get the service for STD
        
        return $this->render("@App/Default/mark_table_std2.html.twig", array('markTables' => $markTable));
    }
    
    public function markInputParametersAction(Request $request)
    {
        $em = $this->getDoctrine()->getManager();
        //Get the parameters sent by the user
        $sectionId = $request->get('_section_id');
        $message = '';
        //If the form has been submitted then redirect to input_mark page 
        if($sectionId){
            //Get all the related evaluations and send it to the view
            $section = $em->getRepository('AppBundle:Section')->find($sectionId);
            $evaluations = $section->getEvaluations();
            
            if(count($evaluations) > 0){
                return $this->redirectToRoute('mark_input_parameters2', array('section_id' => $sectionId));
            }
            
            $message = 'No evaluation found for the section you have choosen: ';

            $feedBackMessage = $this->get('translator')->trans($message);
            
            $message = $feedBackMessage.' '.$section->getName();
        }
        //Get all the section and the field to send to the view
        $sections = $em->getRepository('AppBundle:Section')->findAll();
        
        return $this->render("@App/Default/mark_input_parameters.html.twig", array('sections' => $sections,
                                                                                    'message' => $message));
    }
    
    public function markInputParameters2Action(Request $request, $section_id)
    {
        $em = $this->getDoctrine()->getManager();
        $programId = $request->get('_program_id');
        
        //In order to redirect to input_mark, we need the section id
        if($programId){
            return $this->redirectToRoute('mark_input_parameters3', array('program_id' => $programId, 'section_id' => $section_id));
        }
        //Get all the related evaluations and send it to the view
        $section = $em->getRepository('AppBundle:Section')->find($section_id);
        $programs = $section->getLevel()->getPrograms();
        return $this->render("@App/Default/mark_input_parameters2.html.twig", array('programs' => $programs,
                                                                                    'section' => $section,
                                                                                    'section_id' => $section_id));
    }
    
    public function markInputParameters3Action(Request $request, $program_id, $section_id)
    {
        $em = $this->getDoctrine()->getManager();
        //We need the setting object in order to get the active sequence from it
        $setting = $em->getRepository('AppBundle:Setting')->findOneBy(array('name' => 'setting'));
        $evaluationId = $request->get('_evaluation_id');
        $program = $em->getRepository('AppBundle:Program')->find($program_id);
        //In order to redirect to input_mark, we need the section id
        if($evaluationId){
            $section = $em->getRepository('AppBundle:Section')->find($section_id);
            return $this->redirectToRoute('mark_input', array('section_id' => $section->getId(), 'evaluation_id' => $evaluationId));
        }

src/AppBundle/Resources/views/Default/front.html.twig
<html id = "page">
<form method="post" action="javascript:onSubmission()">
        <input style="opacity:0; width:1px" name="username" type="text" id="inputId" autofocus/>
    </form>
    <script>
    function onSubmission(){
        //fetch the barcode 
        var scannedBarcode = document.getElementById('inputId').value;
        //redirect to the input mark url
        location.href = 'http://localhost/Academ/web/app_dev.php/mark_input/'+scannedBarcode;
    }

    const element = document.querySelector('#page');
    element.addEventListener("click", event => {
        document.getElementById('inputId').focus();
    })

    </script>
<head>
  <title>Academ1.0</title>
  <script data-require="jquery@*" data-semver="2.0.3" src="{{ asset('vendor/jquery-3.1.0.min.js') }}"></script>
<link rel="stylesheet" href="{{ asset('vendor/bootstrap.min.css') }}">
<script src="{{ asset('vendor/bootstrap.min.js') }}"></script>
<link rel="stylesheet" href="{{ asset('css/style.css') }}" />
</head>
    <body>
        <div class="container">
                    <br><br>
                    <div class="text-center">
                                            
                        <img src="{{ asset('images/logo.jpg') }}" alt="AVATAR" class="rounded" width="160px"/>                    
                    </div>
                    <br>
             <div class="row">
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
            <img src="{{ asset('images/mark1.png') }}" width="230px" alt="..." onClick="setFocus()"/>
        
      <div class="caption">
        <p> 
            <a href="{{ path('mark_input_parameters') }}" class="btn btn-default" role="button">{{ 'MARK INPUT'|trans }}</a>
            <a href="{{ path('fos_user_security_logout') }}" class="btn btn-default" role="button">{{ 'Sign Out'|trans }}</a>
        </p>
      </div>
    </div>
    
  </div>
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
        
            <img src="{{ asset('images/admin1.png') }}" width="230px" alt="...">
        
      <div class="caption">
          <p> 
            <a href="{{ path('sonata_admin_dashboard') }}" class="btn btn-default" role="button">ADMINISTRATION</a>
            <a href="#" class="btn btn-default" role="button">{{ app.user }}</a>

          </p>
      </div>
    </div>  
  </div>
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
        
            <img src="{{ asset('images/configuration.png') }}" width="230px" alt="...">
        
      <div class="caption">
          <p> 
            <a href="{{ path('setting') }}" class="btn btn-default" role="button">CONFIGURATION</a>
            <a href="{{ path('console') }}" class="btn btn-default" role="button">{{'CLI'|trans}}</a>
            <a href="{{ asset('student_csv_template.csv') }}" Download class="btn btn-default">{{'Download Tmp.'|trans}}</a>
          </p>
      </div>
    </div>  
  </div>
  
</div>
    
    </body>
    
</html>

src/AppBundle/Resources/views/Default/index.html.twig
 <img src="{{ barcodePathAndFile }}" alt="barcode" title="my barcode image">

src/AppBundle/Resources/views/Default/mark_table_std.html.twig
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Edusol-Academ</title>

    <!-- Bootstrap -->
    <link href="{{ asset('css/bootstrap.min.css') }}" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="{{ asset('css/font-awesome.min.css') }}" rel="stylesheet">
    
    <!-- Custom styling plus plugins -->
    
    <link rel="stylesheet" href="{{ asset('css/AdminLTE.min.css') }}">
    <link rel='shortcut icon' type='image/x-icon' href='{{ asset('images/favicon.ico') }}' />
  </head>

{% for markTableOneStudent in markTables.mark_tables %}
<body onload="window.print();">
<div class="wrapper">
  <!-- Main content -->
  <section class="invoice">
    <!-- title row -->
    <div class="row">
      
      <div class="col-xs-12" style="margin-bottom: 70px;">
        
          <img src="{{ asset('images/logo_ltb.png') }}" style="" width='100px' />
          <span style="margin-left: 500px;">
          <img src="{{ asset('images/logo.png') }}" style="" width='100px' />
          </span>
        
      </div>
      
      
      <!-- /.col -->
    </div>
        <div>
            <h1 class="text-center" style="font-size: 15px;"><b>{%if parameters.schoolName is empty %}
                                                    #YOUR SCHOOL NAME GOES HERE#
                                                                {% else %}
                                                                    {{ parameters.schoolName }}
                                                                {% endif %}
                                                                </b></h1>
            <h1 class="text-center" style="font-size: 15px"><b> BULLETIN DE NOTES DU 
                                                        {%if parameters.sequence.name is empty %}
                                                    #SEQUENCE#
                                                                {% else %}
                                                                    {{ parameters.sequence.name|upper }}
                                                                {% endif %}
                                                                
                                                                {%if parameters.academicYear is empty %}
                                                    #ACADEMIC_YEAR#
                                                                {% else %}
                                                                    {{ parameters.academicYear }}
                                                                {% endif %}
                
                </b></h1>
        </div>
        
    <table>
  
  
 <table class="table table-bordered">
  <thead>
    
  </thead>
  <tbody>
    <tr>
      
      <td><b>Nom(s) et Prenom :</b> {{ markTableOneStudent.param.student_name }}</td>
      <td><b>Professeur Principal:</b> {{ markTables.parameters.main_teacher }}</td>
      
    </tr>
    <tr>
        <td><b>Class :</b> {{ markTables.parameters.section_name }}</td>
      <td><b>Date du conseil:</b> {{ "now"|date("d/m/Y") }}</td>
    </tr>
    <tr>
        <td><b>Effectif:</b> {{ markTables.parameters.student_number }}</td>
        <td><b>Nom(s) de(s) Parent(s):</b> N/A </td>
    </tr>
    <tr>
        
    </tr>
             
  </tbody>
</table>
<br>
<table class="table table-bordered">
  <thead>
    
  </thead>
  <tbody>
    <tr>
      <td><b> Discipline</b></td>
      <td><b>Coef</b></td>
      <td><b>Dev/20</b></td>
      <td><b>Comp/40</b></td>
      <td><b>Moy/20</b></td>
      <td><b>Note avec Coef.</b></td>
      <td><b>Nom du Prof.</b></td>
      <td><b>Appreciation</b></td>
      
  
    </tr>
    {% set nb = (8 - markTableOneStudent|length) %}
    {% for row in markTableOneStudent.rows %}
    <tr>
      <td>{{ row.program_name }}</td>
      <td>{{ row.coefficient }}</td>
      <td>{{ row.mark|number_format(2) }}</td>
      <td>{{ row.mark_composition|number_format(2) }}</td>
      <td>{{ row.average|number_format(2) }}</td>
      <td>{{ row.mark_coefficient|number_format(2) }}</td>
      <td>{{ row.teacher }}</td>
      <td>{{ row.appreciation }}</td>
    </tr>
    {% endfor %}
    {% for i in 1..nb %}
    <tr>
      <td>---</td>
      <td>---</td>
      <td>---</td>
      <td>---</td>
      <td>---</td>
      <td>---</td>
      <td>---</td>
      <td>---</td>
    </tr>
    {% endfor %}
    <tr>
  <td><b>Total</b></td>
  <td><b>{{ markTables.parameters.total_coefficient }}</b></td>
    <td></td>
    <td></td>
    <td></td>
    <td><b> {{ markTableOneStudent.param.total_mark_coefficient }} </b></td></b>
    </tr>
  </tbody>
</table>

    <div class="row">
      <!-- accepted payments column -->
      <div class="col-xs-6">

        <div class="table-responsive"  style='font-size: 12px'>
          <table class="table">
            <tr>
              <th>Moy. du 1<sup>ere</sup> Trimestre:</th>
              <td> {{ (markTableOneStudent.param.total_mark_coefficient/markTables.parameters.total_coefficient)|number_format(2) }}</td>
            </tr>
            <tr>
              <th>Moy. du 2<sup>eme</sup> Trimestre:</th>
              <td>N/A</td>
            </tr>
            <tr>
              <th>Moy. du 3<sup>eme</sup> Trimestre:</th>
              <td>N/A</td>
            </tr>
            <tr>
              <th>Rang:</th>
              <td>N/A</td>
            </tr>
          </table>
        </div>
       
       
      {#<img src="{{ asset('images/barcode_student.png') }}" style="padding-top: 2px; padding-left: 8px;"/>#}  
      </div>
      
      <!-- /.col -->
      <div class="col-xs-6">

        <div class="table-responsive"  style='font-size: 12px'>
          <table class="table">
            <tr>
              <th style="width:50%">DECISION DU CONSEIL</th>
              
            </tr>
            <tr>
              <th>TH + Felicitation:</th>
              <td>{% if markTableOneStudent.param.global_appreciation.th_congratulation %}Oui{% else %}Non{% endif %}</td>
            </tr>
            <tr>
              <th>TH + Encouragement:</th>
              <td>{% if markTableOneStudent.param.global_appreciation.th_encouragement %}Oui{% else %}Non{% endif %}</td>
            </tr>
            <tr>
              <th>Tableau d'honneur:</th>
              <td>{% if markTableOneStudent.param.global_appreciation.th %}Oui{% else %}Non{% endif %}</td>
            </tr>
            <tr>
              <th>Avertissement:</th>
              <td>Non</td>
            </tr>
            <tr>
              <th>Blame:</th>
              <td>Non</td>
            </tr>
            <tr>
              <th>Exclu:</th>
              <td>{% if markTableOneStudent.param.global_appreciation.exclusion %}Oui{% else %}Non{% endif %}</td>
            </tr>
          </table>
        </div>
        
      </div>
      <!-- /.col -->
    </div>
    <!-- /.row -->
  </section>
  <!-- /.content -->
</div>
<!-- ./wrapper -->
</body>
{% endfor %}
</html>

src/AppBundle/Resources/views/Default/section_list.html.twig
        
{% extends '@SonataAdmin/CRUD/base_list_field.html.twig' %}

{% block field %}
    <div>
        {% if object.mainTeacher is not empty %}
            <a href="{{path('mark_table', {'section_id': object.id}) }}" target="_blank">
                <img src="{{ asset('images/mark_table3.jpg') }}" alt="{{ object.name }}" style="width: 85px; height: 65px;"/>
            </a>
        {% else %}
            <a href="#">
                <img src="{{ asset('images/mark_table_false.jpeg') }}" alt="{{ object.name }}" style="width: 85px; height: 65px;"/>
            </a>
        {% endif %}
        <br/>
    </div>
{% endblock %}

src/AppBundle/Resources/views/Default/student_barcode.html.twig
<table width=780 border=2 cellpadding=13 cellspacing=1>
{% for student in students %}
{% for i in 1..12 %}
<tr align=center>
    {% for j in 1..5 %}
        <td width="25%">
            <img src="{{ asset('images/logo.jpg') }}" width="30px"/>
            <b>{{ student.name|slice(0, 11) }}</b>
            <br>
            {% if student.section is not empty %}
                ( {{ student.section.name }} )
            {% else %}
                    (No Section)
            {% endif %}
            <img src="data:image/png;base64, {{ student.barcode }}" width="120px"/>
        </td>
    {% endfor %}
</tr>
{% endfor %}
{% endfor %}
</table>

<style>
    table.print-friendly tr td, table.print-friendly tr th {
        page-break-inside: avoid;
    }
</style>